# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/osx-64/blas-1.0-openblas.conda
https://conda.anaconda.org/conda-forge/osx-64/bzip2-1.0.8-h0d85af4_4.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/ca-certificates-2023.01.10-hecd8cb5_0.conda
https://conda.anaconda.org/conda-forge/osx-64/libbrotlicommon-1.0.9-hb7f2c08_8.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libcxx-16.0.2-hd57cbcb_0.conda
https://conda.anaconda.org/conda-forge/osx-64/libdeflate-1.18-hac1461d_0.conda
https://conda.anaconda.org/conda-forge/osx-64/libffi-3.4.2-h0d85af4_5.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libjpeg-turbo-2.1.5.1-hb7f2c08_0.conda
https://conda.anaconda.org/conda-forge/osx-64/libwebp-base-1.3.0-hb7f2c08_0.conda
https://conda.anaconda.org/conda-forge/osx-64/libzlib-1.2.13-hfd90126_4.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/llvm-openmp-16.0.2-hff08bdf_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/ncurses-6.4-hcec6c5f_0.conda
https://conda.anaconda.org/conda-forge/osx-64/pthread-stubs-0.4-hc929b4f_1001.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/python_abi-3.10-3_cp310.conda
https://conda.anaconda.org/conda-forge/noarch/tzdata-2023c-h71feb2d_0.conda
https://conda.anaconda.org/conda-forge/osx-64/xorg-libxau-1.0.9-h35c211d_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/xorg-libxdmcp-1.1.3-h35c211d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/xz-5.2.10-h6c40b1e_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/yaml-0.2.5-haf1e3a3_0.conda
https://conda.anaconda.org/conda-forge/osx-64/lerc-4.0.0-hb486fe8_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libbrotlidec-1.0.9-hb7f2c08_8.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libbrotlienc-1.0.9-hb7f2c08_8.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libgfortran5-12.2.0-he409387_31.conda
https://conda.anaconda.org/conda-forge/osx-64/libpng-1.6.39-ha978bb4_0.conda
https://conda.anaconda.org/conda-forge/osx-64/libsqlite-3.40.0-ha978bb4_1.conda
https://conda.anaconda.org/conda-forge/osx-64/libxcb-1.13-h0d85af4_1004.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/lz4-c-1.9.4-hf0c8a7f_0.conda
https://conda.anaconda.org/conda-forge/osx-64/openssl-3.1.0-h8a1eda9_2.conda
https://conda.anaconda.org/conda-forge/osx-64/readline-8.2-h9e318b2_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/tbb-2021.8.0-ha357a0b_0.conda
https://conda.anaconda.org/conda-forge/osx-64/tk-8.6.12-h5dbffcc_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/zlib-1.2.13-hfd90126_4.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/brotli-bin-1.0.9-hb7f2c08_8.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/freetype-2.12.1-h3f81eb7_1.conda
https://conda.anaconda.org/conda-forge/osx-64/libgfortran-5.0.0-11_3_0_h97931a8_31.conda
https://repo.anaconda.com/pkgs/main/osx-64/libllvm11-11.1.0-h46f1229_6.conda
https://conda.anaconda.org/conda-forge/osx-64/python-3.10.10-he7542f4_0_cpython.conda
https://repo.anaconda.com/pkgs/main/osx-64/zstd-1.5.5-hc035e20_0.conda
https://conda.anaconda.org/conda-forge/osx-64/brotli-1.0.9-hb7f2c08_8.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/certifi-2022.12.7-py310hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/click-8.0.4-py310hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/cloudpickle-2.2.1-py310hecd8cb5_0.conda
https://conda.anaconda.org/conda-forge/noarch/cycler-0.11.0-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/fsspec-2023.4.0-py310hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/heapdict-1.0.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/idna-3.4-py310hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/itsdangerous-2.0.1-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/osx-64/kiwisolver-1.4.4-py310ha23aa8a_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libopenblas-0.3.21-openmp_h429af6e_3.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libtiff-4.5.0-hedf67fa_6.conda
https://repo.anaconda.com/pkgs/main/osx-64/llvmlite-0.39.1-py310h8346a28_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/locket-1.0.0-py310hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/markupsafe-2.1.1-py310hca72f7f_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/msgpack-python-1.0.3-py310haf03e11_0.conda
https://conda.anaconda.org/conda-forge/noarch/munkres-1.1.4-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/networkx-3.1-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/packaging-23.1-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/parmap-1.6.0-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/psutil-5.9.0-py310hca72f7f_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pycparser-2.21-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/noarch/pyparsing-3.0.9-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/pysocks-1.7.1-py310hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/python-lmdb-1.4.1-py310hcec6c5f_0.conda
https://conda.anaconda.org/conda-forge/noarch/python-tzdata-2023.3-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/pytz-2023.3-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/pyyaml-6.0-py310h6c40b1e_1.conda
https://conda.anaconda.org/conda-forge/noarch/setuptools-67.7.2-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/six-1.16.0-pyh6c4a22f_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/smart_open-5.2.1-py310hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/sortedcontainers-2.4.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/tblib-1.7.0-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/noarch/threadpoolctl-3.1.0-pyh8a188c0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/toolz-0.12.0-py310hecd8cb5_0.conda
https://conda.anaconda.org/conda-forge/osx-64/tornado-6.3-py310h90acd4f_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/typing_extensions-4.5.0-py310hecd8cb5_0.conda
https://conda.anaconda.org/conda-forge/osx-64/unicodedata2-15.0.0-py310h90acd4f_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/wheel-0.40.0-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/zipp-3.11.0-py310hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/cffi-1.15.1-py310h6c40b1e_3.conda
https://repo.anaconda.com/pkgs/main/osx-64/cytoolz-0.12.0-py310hca72f7f_0.conda
https://conda.anaconda.org/conda-forge/osx-64/fonttools-4.39.3-py310h90acd4f_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/importlib-metadata-6.0.0-py310hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/jinja2-3.1.2-py310hecd8cb5_0.conda
https://conda.anaconda.org/conda-forge/noarch/joblib-1.2.0-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/lcms2-2.15-h2dcdeff_1.conda
https://conda.anaconda.org/conda-forge/osx-64/libblas-3.9.0-16_osx64_openblas.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/numpy-base-1.23.5-py310h992e150_0.conda
https://conda.anaconda.org/conda-forge/osx-64/openjpeg-2.5.0-h13ac156_2.conda
https://repo.anaconda.com/pkgs/main/noarch/partd-1.2.0-pyhd3eb1b0_1.conda
https://conda.anaconda.org/conda-forge/noarch/pip-23.1.2-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/python-dateutil-2.8.2-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/werkzeug-2.2.3-py310hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/zict-2.2.0-py310hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/brotlipy-0.7.0-py310hca72f7f_1002.conda
https://repo.anaconda.com/pkgs/main/osx-64/cryptography-39.0.1-py310hf6deb26_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/dask-core-2023.4.1-py310hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/flask-2.2.2-py310hecd8cb5_0.conda
https://conda.anaconda.org/conda-forge/osx-64/libcblas-3.9.0-16_osx64_openblas.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/liblapack-3.9.0-16_osx64_openblas.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/numpy-1.23.5-py310he50c29a_0.conda
https://conda.anaconda.org/conda-forge/osx-64/pillow-9.5.0-py310h6b2f720_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/bokeh-2.4.3-py310hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/bottleneck-1.3.5-py310h4e76f89_0.conda
https://conda.anaconda.org/conda-forge/osx-64/contourpy-1.0.7-py310ha23aa8a_0.conda
https://conda.anaconda.org/conda-forge/osx-64/libfaiss-1.7.2-h88b3cc4_3_cpu.conda
https://conda.anaconda.org/conda-forge/osx-64/libfaiss-avx2-1.7.2-h1234567_3_cpu.conda
https://repo.anaconda.com/pkgs/main/osx-64/numba-0.56.4-py310h3ea8b11_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/numexpr-2.8.4-py310he50c29a_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/pyopenssl-23.0.0-py310hecd8cb5_0.conda
https://conda.anaconda.org/conda-forge/noarch/python-louvain-0.16-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/osx-64/scipy-1.8.0-py310h47774c9_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/faiss-1.7.2-py310h340760d_3_cpu.conda
https://repo.anaconda.com/pkgs/main/osx-64/gensim-4.3.0-py310h3ea8b11_0.conda
https://conda.anaconda.org/conda-forge/osx-64/matplotlib-base-3.7.1-py310he725631_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/pandas-1.5.3-py310h3ea8b11_0.conda
https://conda.anaconda.org/conda-forge/osx-64/scikit-learn-1.2.2-py310h311060b_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/urllib3-1.26.15-py310hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/distributed-2023.4.1-py310hecd8cb5_0.conda
https://conda.anaconda.org/bioconda/noarch/markov_clustering-0.0.6-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/matplotlib-3.7.1-py310h2ec42d9_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/modin-core-0.20.1-py310hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/seaborn-0.12.2-py310hecd8cb5_0.conda
https://conda.anaconda.org/svalkiers/noarch/clustcr-1.0.2+17.gdb12543-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/dask-2023.4.1-py310hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/modin-dask-0.20.1-py310hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/modin-0.20.1-py310hecd8cb5_0.conda
